### ISSUE TITLE
Error when iterating on certain types - undefined method 'form'

### ISSUE THREAD

**Issue by jcran** [intrigueio/intrigue-core#15]
```
20:39:23 web.1    | 2015-08-24 20:39:23 - NoMethodError - undefined method `form' for false:FalseClass:
20:39:23 web.1    | 	/Users/jcran/work/intrigue/projects/intrigue-core/app/views/index.erb:45:in `block in singleton class'
20:39:23 web.1    | 	/Users/jcran/work/intrigue/projects/intrigue-core/app/views/index.erb:-6:in `instance_eval'
20:39:23 web.1    | 	/Users/jcran/work/intrigue/projects/intrigue-core/app/views/index.erb:-6:in `singleton class'
20:39:23 web.1    | 	/Users/jcran/work/intrigue/projects/intrigue-core/app/views/index.erb:-8:in `__tilt_70289781187520'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in `render'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:666:in `erb'
20:39:23 web.1    | 	/Users/jcran/work/intrigue/projects/intrigue-core/core.rb:106:in `block (2 levels) in <class:IntrigueApp>'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
20:39:23 web.1    | 	/Users/jcran/.rvm/gems/ruby-2.1.5@core/gems/sinatra-1.4.6
```

**Comment by jcran** [comment]
Can't repro
