### ISSUE TITLE
Fix error when starting task with core-cli.rb

### ISSUE THREAD

**Issue by jcran** [intrigueio/intrigue-core#31]
```
jcran@masterblaster:~/core$ bundle exec ./core-cli.rb start uri_spider Uri#http://intrigue.io
Got entity: {"type"=>"Uri", "attributes"=>{"name"=>"http://intrigue.io"}}
Payload: {"task"=>"uri_spider", "options"=>[], "entity"=>{"type"=>"Uri", "attributes"=>{"name"=>"http://intrigue.io"}}}
/home/jcran/.rvm/gems/ruby-2.2.0@core/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /home/jcran/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
	from ./core-cli.rb:377:in `_background'
	from ./core-cli.rb:121:in `single'
	from ./core-cli.rb:111:in `start'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/jcran/.rvm/gems/ruby-2.2.0@core/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from ./core-cli.rb:384:in `<main>'
jcran@masterblaster:~/core$ 
```

**Comment by jcran** [comment]
Fixed, but note that core-cli.rb currently depends on having the API running on :7777 - do we want to remove this dep?

**Comment by jcran** [comment]
Fixed.
