### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by KINGSABRI** [intrigueio/intrigue-core#34]
Hi, 
I'm trying to install the project on Kubuntu 15.4 
Ruby version is `ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]`
All required gems are installed using bundle.

Once I run the application, I get the following error 
```
sudo foreman start
00:35:26 web.1    | started with pid 28570
00:35:26 worker.1 | started with pid 28571
00:35:26 web.1    | /usr/lib/ruby/vendor_ruby/bundler/source/git.rb:191:in `rescue in load_spec_files': https://github.com/intrigueio/arachnid.git (at master) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/source/git.rb:188:in `load_spec_files'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/source/path.rb:92:in `local_specs'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/source/git.rb:159:in `specs'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:211:in `block (2 levels) in index'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:209:in `each'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:209:in `block in index'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/index.rb:9:in `build'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:206:in `index'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:140:in `specs'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:185:in `specs_for'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:174:in `requested_specs'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/environment.rb:18:in `requested_specs'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:13:in `setup'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler.rb:127:in `setup'
00:35:26 web.1    |     from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:18:in `<top (required)>'
00:35:26 worker.1 | /usr/lib/ruby/vendor_ruby/bundler/source/git.rb:191:in `rescue in load_spec_files': https://github.com/intrigueio/arachnid.git (at master) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
00:35:26 web.1    |     from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/source/git.rb:188:in `load_spec_files'
00:35:26 web.1    |     from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/source/path.rb:92:in `local_specs'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/source/git.rb:159:in `specs'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:211:in `block (2 levels) in index'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:209:in `each'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:209:in `block in index'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/index.rb:9:in `build'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:206:in `index'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:140:in `specs'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:185:in `specs_for'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:174:in `requested_specs'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/environment.rb:18:in `requested_specs'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:13:in `setup'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler.rb:127:in `setup'
00:35:26 worker.1 |     from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:18:in `<top (required)>'
00:35:26 worker.1 |     from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
00:35:26 worker.1 |     from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
00:35:26 web.1    | exited with code 1
00:35:26 system   | sending SIGTERM to all processes
00:35:26 worker.1 | exited with code 1
```

**Comment by jcran** [comment]
@KINGSABRI Still hitting this? Can't repro, probably fixed.

**Comment by jcran** [comment]
Closing this out due to inactivity.
