### ISSUE TITLE
403 FORBIDDEN - pipl task broken?

### ISSUE THREAD

**Issue by jcran** [intrigueio/intrigue-core#41]
Probably needs an update to the latest Pipl Api

```
48:37 task-worker.1 | 2016-05-01T15:48:37.662Z 47284 TID-oxtuqze8g Intrigue::SearchPiplTask JID-609091bc20847785a7ad6065 INFO: fail: 1.86 sec
08:48:37 task-worker.1 | 2016-05-01T15:48:37.662Z 47284 TID-oxtuqze8g WARN: {"class"=>"Intrigue::SearchPiplTask", "args"=>[2472, []], "retry"=>true, "queue"=>"task", "backtrace"=>true, "jid"=>"609091bc20847785a7ad6065", "created_at"=>1462117715.5040362, "enqueued_at"=>1462117715.5041, "error_message"=>"403 FORBIDDEN", "error_class"=>"OpenURI::HTTPError", "failed_at"=>1462117717.457272, "retry_count"=>0, "error_backtrace"=>["/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:359:in `open_http'", "/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'", "/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'", "/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `catch'", "/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'", "/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'", "/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:717:in `open'", "/Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:35:in `open'", "/Users/jcran/work/intrigue/projects/intrigue-core/lib/client/search/pipl.rb:20:in `search'", "/Users/jcran/work/intrigue/projects/intrigue-core/lib/tasks/search_pipl.rb:40:in `run'", "/Users/jcran/work/intrigue/projects/intrigue-core/lib/tasks/base.rb:67:in `perform'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'", "/Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'"]}
08:48:37 task-worker.1 | 2016-05-01T15:48:37.662Z 47284 TID-oxtuqze8g WARN: OpenURI::HTTPError: 403 FORBIDDEN
08:48:37 task-worker.1 | 2016-05-01T15:48:37.662Z 47284 TID-oxtuqze8g WARN: /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:359:in `open_http'
08:48:37 task-worker.1 | /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
08:48:37 task-worker.1 | /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
08:48:37 task-worker.1 | /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
08:48:37 task-worker.1 | /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
08:48:37 task-worker.1 | /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
08:48:37 task-worker.1 | /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:717:in `open'
08:48:37 task-worker.1 | /Users/jcran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:35:in `open'
08:48:37 task-worker.1 | /Users/jcran/work/intrigue/projects/intrigue-core/lib/client/search/pipl.rb:20:in `search'
08:48:37 task-worker.1 | /Users/jcran/work/intrigue/projects/intrigue-core/lib/tasks/search_pipl.rb:40:in `run'
08:48:37 task-worker.1 | /Users/jcran/work/intrigue/projects/intrigue-core/lib/tasks/base.rb:67:in `perform'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'
08:48:37 task-worker.1 | /Users/jcran/.rvm/gems/ruby-2.3.0@core/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
08:48:38 task-worker.1 | [ ] : Port: 22
```

**Comment by jcran** [comment]
No longer repros.
