### ISSUE TITLE
Docker quickstart is broken 

### ISSUE THREAD

**Issue by dagelf** [intrigueio/intrigue-core#456]
From https://core.intrigue.io/docker-one-liner:
```
$ docker run -e LANG=C.UTF-8 --memory=8g -p 0.0.0.0:7777:7777 -it "intrigueio/intrigue-core:latest"
```

Produces:
```
2024-11-27T19:52:24.578Z pid=1760 tid=1790 WARN: /home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:156:in `exec'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:156:in `block in execute_query'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:156:in `execute_query'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:144:in `block in execute'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:120:in `check_disconnect_errors'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:144:in `execute'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:500:in `_execute'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:318:in `block (2 levels) in execute'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:522:in `check_database_errors'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:318:in `block in execute'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:318:in `execute'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/dataset/actions.rb:1093:in `execute'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/adapters/postgres.rb:614:in `fetch_rows'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/dataset/actions.rb:152:in `each'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/dataset/actions.rb:86:in `columns!'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/dataset/actions.rb:76:in `columns'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:242:in `columns'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:788:in `block (2 levels) in get_db_schema'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:686:in `block in check_non_connection_error'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/database/transactions.rb:201:in `block in transaction'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/database/transactions.rb:195:in `transaction'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:686:in `check_non_connection_error'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:788:in `block in get_db_schema'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:821:in `get_db_schema'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:606:in `set_dataset'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sequel-5.45.0/lib/sequel/model/base.rb:869:in `inherited'
/home/ubuntu/core/app/models/alias_group.rb:4:in `<module:Model>'
/home/ubuntu/core/app/models/alias_group.rb:3:in `<module:Core>'
/home/ubuntu/core/app/models/alias_group.rb:2:in `<module:Intrigue>'
/home/ubuntu/core/app/models/alias_group.rb:1:in `<top (required)>'
/home/ubuntu/core/app/all.rb:26:in `require_relative'
/home/ubuntu/core/app/all.rb:26:in `<top (required)>'
/home/ubuntu/core/core.rb:265:in `require_relative'
/home/ubuntu/core/core.rb:265:in `<class:CoreApp>'
/home/ubuntu/core/core.rb:145:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:269:in `require'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:269:in `boot_application'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:37:in `run'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sidekiq-6.2.1/bin/sidekiq:31:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/bin/sidekiq:23:in `load'
/home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/bin/sidekiq:23:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/ubuntu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/home/ubuntu/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/ubuntu/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
Connecting to Redis Server at: redis://127.0.0.1:6379/
2024-11-27T19:52:29.459Z pid=1766 tid=178y INFO: Booting Sidekiq 6.2.1 with redis options {:url=>"redis://127.0.0.1:6379/"}
Configuring reliable fetch if it's available!
2024-11-27T19:52:29.584Z pid=1766 tid=178y WARN: Sequel::DatabaseError: PG::UndefinedTable: ERROR:  relation "alias_groups" does not exist
LINE 1: SELECT * FROM "alias_groups" LIMIT 1
                      ^
```

**Comment by jcran** [comment]
Thanks for the report, not able to repro on a clean system. Error indicates it's having trouble hitting the associated postgres which is also configured in the same container, so maybe pg errored earlier in the process? 

Keep in mind this project is several years out of date. Would recommend looking at:
 - Amass
 - Project Discovery
 - RunZero
 - Sn1per https://github.com/1N3/Sn1per

and the others in this list https://github.com/attacksurge/awesome-attack-surface-monitoring
