### ISSUE TITLE
uninitialized constant RestClient::MaxRedirectsReached

### ISSUE THREAD

**Issue by securitykitten** [intrigueio/intrigue-core#90]
Uploading some of the errors I've encountered to track them.
 
```
2019-06-11T14:14:21.505Z 1022 TID-gpg9guj3u DEBUG: enqueued retry: {"class":"Intrigue::Task::Enrich::DnsRecord","queue":"task_enrichment","retry":true,"args":[22001],"jid":"c9de6e3cca2114f6b0045de3","created_at":1560195136.510924,"enqueued_at":1560195136.5109646,"error_message":"uninitialized constant RestClient::MaxRedirectsReached","error_class":"NameError","failed_at":1560262434.4320893,"retry_count":0}
```

**Comment by securitykitten** [comment]
More contextual logging from the error
```
#<Thread:0x00007fd0a42f4460@/core/lib/tasks/helpers/services.rb:75 run> terminated with exception (report_on_exception is true):
/core/lib/tasks/helpers/services.rb:341:in `rescue in _gather_http_response': uninitialized constant RestClient::MaxRedirectsReached (NameError)
        from /core/lib/tasks/helpers/services.rb:296:in `_gather_http_response'
        from /core/lib/tasks/helpers/services.rb:92:in `block (2 levels) in _create_network_service_entity'
```

**Comment by securitykitten** [comment]
After some digging it looks like this was removed in newer versions of restclient.

According to https://github.com/rest-client/rest-client/blob/master/history.md
```
Remove RestClient::MaxRedirectsReached in favor of the normal ExceptionWithResponse subclasses. This makes the response accessible on the exception object as .response, making it possible for callers to tell what has actually happened when the redirect limit is reached.
```

**Comment by jcran** [comment]
no longer able to repro this, re-open if you're still hitting it.
